@host=http://localhost:5190
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MWQ4OGE1MC0yODVkLTRmNWEtODY2NC0xMjYwMmI4ZGQ3ODkiLCJlbWFpbCI6InRzdW5pdGlAdGVzdC5jb20iLCJyb2xlIjoiU0VMTEVSIiwianRpIjoiN2JkZWRhMTMtMjYzMy00OWI4LWE1ZDYtMjY3Y2ZkMzhmYmRjIiwiZXhwIjoxNzUyNzExMDg2LCJpc3MiOiJMdWtraSIsImF1ZCI6Ikx1a2tpIn0.AZzgBOv7Fen5lnys_00UBaedp-TngHYyvNimP_l1nVY

POST {{host}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "string",
  "description": "string",
  "targetGroup": "MALE",
  "price": {
    "amount": 100.0,
    "currency": "USD"
  },
  "images": [
    {file}
  ],
  "inStockProducts": [
    {
      "quantity": 100,
      "size": "L"
    }
  ],
  "categoryId": "123e4567-e89b-12d3-a456-426614174000"
}