@host=http://localhost:5190
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjUzMzEzZS0yNDlmLTQ4MTktYmM3ZC0zOGNhZTAyYzI1ZjMiLCJlbWFpbCI6InRzdW5pdGlAdGVzdC5jb20iLCJyb2xlIjoiU0VMTEVSIiwianRpIjoiOThjZjFlZDMtYjVmYS00MmZhLThmYjktMjRmODJmYTNlOTcyIiwiZXhwIjoxNzUyNTE1NTQ3LCJpc3MiOiJMdWtraSIsImF1ZCI6Ikx1a2tpIn0.r_VHTFWstrRgrXFrB5I1eLmXso4GhRh-UYnEpuOtar0

POST {{host}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "string",
  "description": "string",
  "targetGroup": "MALE",
  "price": {
    "amount": 100.0,
    "currency": "USD"
  },
  "images": [
    "https://example.com/image.jpg"
  ],
  "inStockProducts": [
    {
      "quantity": 100,
      "size": "L"
    }
  ],
  "categoryId": "123e4567-e89b-12d3-a456-426614174000"
}