@host=http://localhost:5190
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYjc1OWY3OC1jZmU1LTQ5OTItYTZkNy1kZWEyN2M2YjllZDkiLCJlbWFpbCI6InRzdW5pdGlAdGVzdC5jb20iLCJyb2xlIjoiU0VMTEVSIiwianRpIjoiOGRjMTQ2YzYtMmUxNi00YTQzLWI4OTMtMmJjMDQ5NjFhMmRiIiwiZXhwIjoxNzUyMTAwNzY2LCJpc3MiOiJMdWtraSIsImF1ZCI6Ikx1a2tpIn0.YRqcJsXE-ostuJ9aLKbVnXlnObLsFzAym19hWWDcUhw

POST {{host}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "string",
  "description": "string",
  "targetGroup": "MALE",
  "price": {
    "amount": 100.0,
    "currency": "USD"
  },
  "images": [
    "https://example.com/image.jpg"
  ],
  "inStockProducts": [
    {
      "quantity": 100,
      "size": "L"
    }
  ],
  "categoryId": "123e4567-e89b-12d3-a456-426614174000"
}