@host=http://localhost:5190

POST {{host}}/auth/register/
Content-Type: application/json

{
  "BrandName": "TestBrand",
  "firstName": "Tsuniti",
  "lastName": "TestSurname",
  "email": "tsuniti@test.com",
  "password": "Tsuniti123!"
}