@host=http://localhost:5190

POST {{host}}/auth/register/
Content-Type: application/json

{
  "brandName": "TestBrand",
  "firstName": "Tsuniti",
  "lastName": "TestSurname",
  "email": "tsuniti1@test.com",
  "password": "Tsuniti123!"
}